apiVersion: v1
kind: Service
metadata:
  name: pdf-reader-admin-service
  namespace: default
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local  # Ensures traffic only goes to nodes running the pod
  selector:
    app: pdf-reader-admin
  ports:
    - port: 8083
      targetPort: 8083
      protocol: TCP
