apiVersion: v1
kind: Service
metadata:
  name: pdf-reader-client-service
  namespace: default
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local  # Ensures traffic only goes to nodes running the pod
  selector:
    app: pdf-reader-client
  ports:
    - port: 8084
      targetPort: 8084
      protocol: TCP
