apiVersion: v1
kind: Service
metadata:
  name: pdf-reader-client-service
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing  # 👈 This makes it public
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local  # Ensures traffic only goes to nodes running the pod
  selector:
    app: pdf-reader-client
  ports:
    - port: 80
      targetPort: 8084
      protocol: TCP
