apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-reader-admin
  labels:
    app: pdf-reader-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdf-reader-admin
  template:
    metadata:
      labels:
        app: pdf-reader-admin
    spec:
      containers:
      - name: pdf-reader-admin
        image: pdf-reader-admin:latest  # This image is expected to be loaded on the nodes (e.g., via a custom image loader)
        ports:
        - containerPort: 8083
        command: ["streamlit", "run", "./Admin/admin.py",
                  "--server.address=0.0.0.0",
                  "--server.port=8083",
                  "--server.enableCORS=false",
                  "--server.enableXsrfProtection=false"]
        readinessProbe:  # 👈 AWS needs this to mark the pod as healthy!
          httpGet:
            path: /
            port: 8083
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8083
          initialDelaySeconds: 5
          periodSeconds: 10
